### ISSUE TITLE
Question: How do you handle (breaking) updates?

### ISSUE THREAD

**Issue by pico-prob** [jugendpresse/docker-antragsgruen#2]
I stumbled over the [creator's notes on upgrading](https://github.com/CatoTH/antragsgruen/blob/main/docs/UPGRADING.md). I am wondering: 

- Do you add anything to handle braking upgrades?
- Should I use a static image version to avoid breaking?

Thank you for the Image, BTW!

**Comment by macwinnie** [comment]
Hi @pico-prob,

sorry for the late response!

In general, static image versions can help braking in general – the version tags with all three (MAJOR.MINOR.PATCH) version parts are only built once, the other version tags are re-built each time a new version matching that version part is published.

At the moment, there is no automation planned to fix the database with the queries from the URL provided or other braking changes. They should be embedded into the base software by @CatoTH – probably by some db migrations or sth. like that.

Hope, that answer is useful at the moment ... 
Best
macwinnie

**Comment by macwinnie** [comment]
(But I think, as I read the document, `yii migrate` does the migration of database and that command is executed on each startup of the container ...)

**Comment by CatoTH** [comment]
Yes `./yii migrate` should do everything that is necessary. Maybe flush the caches (`./yii cache/flush-all`) just to make sure.
The queries explicitly mentioned in the Upgrade document are from before the web-based updater was introduced with version 4 - that is, from before mid-2018. Since then, everything should be covered by the migrations.

**Comment by pico-prob** [comment]
So to my understanding, there's no need to keep the version static (besides the general caution).
Thank you!

**Comment by macwinnie** [comment]
Perfekt, so I'll close this issue – thanks for your response, @CatoTH =)
