### ISSUE TITLE
Security Concerns Traefik Configuration

### ISSUE THREAD

**Issue by philippschuetz** [jugendpresse/docker-antragsgruen#7]
Regarding https://github.com/devops-ansible/docker-antragsgruen/blob/master/docker-compose-traefik.yml.
It should be avoided mounting the docker socket directly as a volume in a container. A way to resolve this issue would be to use a proxy for the docker socket.

Resources:
[https://cheatsheetseries.owasp.org/cheatsheets/Docker_Security_Cheat_Sheet.html#rule-1-do-not-expose-the-docker-daemon-socket-even-to-the-containers]()
[https://github.com/Tecnativa/docker-socket-proxy]()
[https://github.com/traefik/traefik/issues/4174]()

**Comment by macwinnie** [comment]
Hi @philipp-schuetz,
the `docker-compose` files are meant to be examples – and as such stand-alone self-explaining ones. As proxies and other options would not be configured just using a single boot-up `docker-compose` file but need further, detailed explanations, I'd like to keep the file as it is – probably with a caps-lock written warning as a comment above of the line and some links on how-tos in the www on how to overcome the security issues on that. Maybe you want to create a PR with some suggestions on that? =)
Thanks a lot!
Martin
